### ISSUE TITLE
i cannot run    kds.mice(2)

### ISSUE THREAD

**Issue by ccd545235100** [AnotherSamWilson/miceforest#28]
D:\anaconda\lib\site-packages\lightgbm\engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
D:\anaconda\lib\site-packages\lightgbm\basic.py:1491: UserWarning: 'silent' argument is deprecated and will be removed in a future release of LightGBM. Pass 'verbose' parameter via 'params' instead.
  _log_warning("'silent' argument is deprecated and will be removed in a future release of LightGBM. "
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-169c3981fdb0> in <module>
----> 1 kds.mice(2)

D:\anaconda\lib\site-packages\miceforest\ImputationKernel.py in mice(self, iterations, verbose, variable_parameters, **kwlgb)
    844                         )
    845                         imp_values = np.array(
--> 846                             self.mean_match_function(
    847                                 mmc=self.mean_match_candidates[var],
    848                                 model=current_model,

D:\anaconda\lib\site-packages\miceforest\mean_matching_functions.py in default_mean_match(mmc, model, candidate_features, bachelor_features, candidate_values, random_state)
    108             # balanced_tree = False fixes a recursion issue for some reason.
    109             # https://github.com/scipy/scipy/issues/14799
--> 110             kd_tree = KDTree(candidate_preds, leafsize=16, balanced_tree=False)
    111             _, knn_indices = kd_tree.query(bachelor_preds, k=mmc, workers=-1)
    112 

TypeError: __init__() got an unexpected keyword argument 'balanced_tree'

**Comment by ccd545235100** [comment]
how can i fix this

**Comment by samFarrellDay** [comment]
Try updating scipy, they changed the KDtree implementation around version 1.6 or so. It looks like lightgbm also changed the way verbosity works in 3.3.1... I'll need to update that.

**Comment by ChrisPapadakis** [comment]
Updating scipy (=>1.6.0) worked for me :D
